export const metadata = {
  title: { default: 'Cart| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};
export default function CartPage() {
  return <div>Cart</div>;
}
