export const metadata = {
  title: { default: 'About| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};
export default function AboutPage() {
  return <div>About page</div>;
}
