import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { ReactNode } from 'react';
import CookieBanner from './CookieBanner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page | Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookieBanner />
        <nav>
          <div>
            {/* This is not optimized */}
            {/* <a href="/">Home</a> */}
            {/* This is optimized */}
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
            <Link href="/checkout">Checkout</Link>
            <Link href="/cart">Cart</Link>
            <Link href="/thanks">Thanks</Link>
          </div>

          {Math.floor(Math.random() * 10)}
        </nav>

        {props.children}
      </body>
    </html>
  );
}
