import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            {/* use 'Link'(built in nextjs f) instead of 'a' for optimisation */}
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/checkout">Checkout</Link>
            <Link href="/products">Products</Link>
            <Link href="/thanks">Thanks</Link>
          </div>
          {Math.floor(Math.random() * 10)}
        </nav>

        {children}
      </body>
    </html>
  );
}
