export const metadata = {
  title: { default: 'Thanks| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};
export default function ThanksPage() {
  return <title>Thank you for your order</title>;
}
