export const metadata = {
  title: { default: 'Checkout| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};
export default function CheckoutPage() {
  return <div>Checkout page</div>;
}
