import styles from './Check.scss';

export const metadata = {
  title: { default: 'Checkout| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};

export default function CheckoutPage() {
  return (
    <div className="checkout-container">
      <h1 className="checkout-title">Checkout</h1>
      <form className="checkout-form">
        <h2 className="section-title">Shipping Information</h2>
        <div className="form-field">
          <label htmlFor="firstName">First Name:</label>
          <input
            type="text"
            name="firstName"
            id="firstName"
            placeholder="First Name"
            data-test-id="checkout-first-name"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="lastName">Last Name:</label>
          <input
            type="text"
            name="lastName"
            id="lastName"
            placeholder="Last Name"
            data-test-id="checkout-last-name"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="email">Email:</label>
          <input
            type="email"
            name="email"
            id="email"
            placeholder="Email"
            data-test-id="checkout-email"
            className="input-field"
          />
        </div>
        {/* Add more shipping information fields in a similar structure */}
        <div className="form-field">
          <label htmlFor="address">Address:</label>
          <input
            type="text"
            name="address"
            id="address"
            placeholder="Address"
            data-test-id="checkout-address"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="city">City:</label>
          <input
            type="text"
            name="city"
            id="city"
            placeholder="City"
            data-test-id="checkout-city"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="postalCode">Postal Code:</label>
          <input
            type="text"
            name="postalCode"
            id="postalCode"
            placeholder="Postal Code"
            data-test-id="checkout-postal-code"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="country">Country:</label>
          <input
            type="text"
            name="country"
            id="country"
            placeholder="Country"
            data-test-id="checkout-country"
            className="input-field"
          />
        </div>

        <h2 className="section-title">Payment Information</h2>
        {/* Add payment information fields as well as the Total and Confirm Order button */}
        <div className="form-field">
          <label htmlFor="creditCard">Credit Card Number:</label>
          <input
            type="text"
            name="creditCard"
            id="creditCard"
            placeholder="Credit Card Number"
            data-test-id="checkout-credit-card"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="expirationDate">Expiration Date:</label>
          <input
            type="text"
            name="expirationDate"
            id="expirationDate"
            placeholder="Expiration Date"
            data-test-id="checkout-expiration-date"
            className="input-field"
          />
        </div>
        <div className="form-field">
          <label htmlFor="securityCode">Security Code:</label>
          <input
            type="text"
            name="securityCode"
            id="securityCode"
            placeholder="Security Code"
            data-test-id="checkout-security-code"
            className="input-field"
          />
        </div>

        <h2 className="total-title">Total:</h2>

        <button
          type="submit"
          data-test-id="checkout-confirm-order"
          className="confirm-button"
        >
          Confirm Order
        </button>
      </form>
    </div>
  );
}
