import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../database/products';

export const metadata = {
  title: { default: 'Products| Kali app', template: '%s | Kali app' },
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  const products = getProducts();
  return (
    <div>
      <h1>Order yourself a cyber attack</h1>
      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link href={`/products/${product.id}`}>{product.firstName}</Link>
            <Image
              src={`/images/${product.firstName}.png`}
              alt={product.firstName}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
}
